### ISSUE TITLE
Analysis for assumed 'static' network organisation

### ISSUE THREAD

**Issue by gmschroe** [roschkoenig/Network_Analysis_for_Epilepsy_Surgery#14]
- [ ] **Define problem**
- [ ] **Literature summary** 
  - [ ] [Kramer et al. 2011: "Emergence of persistent networks in long-term intracranial EEG recordings"](http://www.jneurosci.org/content/jneuro/31/44/15757.full.pdf) *to be read*
- [ ] **Proposed solution and dataset** 
- [ ] **Analysis scripts written** 
- [ ] **Summary of the results**

**Comment by yujiangwang** [comment]
I've copied the Kramer link into the [temporal variability issue](https://github.com/roschkoenig/Network_Analysis_for_Epilepsy_Surgery/issues/3), and closed this issue. Hope that's ok.

**Comment by gmschroe** [comment]
That's fine - I wasn't quite sure what the distinction between this topic and the temporal variability one were, myself!
